#
# file:		test_pull_to_master.yml
#

name: test_pull_to_master
on:
    pull_request:
        branches: [ master ]

jobs:

    # matrix for debian linuxes (for now ubuntu-18.04 and ubuntu-20.04)
    unixes:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [ubuntu-22.04, ubuntu-24.04, macos-latest]
        steps:
            - name: Checking out repository
              uses: actions/checkout@v3
    
            - name: Preparing host for ${{ matrix.os }}
              run: ./scripts/unix_prepare_host.sh
      
            - name: Preparing repository for ${{ matrix.os }}
              run: ./scripts/unix_prepare_repository.sh

            - name: Building
              run: ./scripts/unix_build_all.sh

            - name: testing test apps
              run: ./scripts/unix_run_tests.sh
            
    # This is for windows
    windows:
        runs-on: windows-latest
        steps:
            - name: Checking out repository
              uses: actions/checkout@v3

            - name: Setup MSBuild.exe
              uses: microsoft/setup-msbuild@v1.1

            - name: Setup developer command prompt
              uses: ilammy/msvc-dev-cmd@v1

            - name: Developer host preparation
              run: cmd /C "call .\scripts\windows_prepare_host.bat"
              #working-directory: core

            - name: Repository preparation
              run: cmd /C "call .\scripts\windows_prepare_repository.bat"

            - name: Compiling cinternal all tests
              run: >
                cmd /C "call .\scripts\windows_build_all.bat"

            - name: testing test apps
              run: cmd /C "call .\scripts\windows_run_tests.bat"
